arangements and better information on activities

diff --git a/src/shell/kcroninit b/src/shell/kcroninit
--- a/src/shell/kcroninit
+++ b/src/shell/kcroninit
@@ -78,24 +78,6 @@ if [[ $# -ne 0 ]]; then
 fi
 
 ###########################################################
-#           CONFIRM
-###########################################################
-echo "kcroninit creates principal ${FULLPRINCIPAL} and/or extracts its keys into a keytab."
-echo "This principal is used by the kcron utility for authentication."
-echo "You need to know the password for ${ADMPRINCIPAL} to continue."
-while true; do
-    read -r -p 'Do you want to continue? (y/n)' yn
-    case ${yn} in
-    [Yy]*) break ;;
-    [Nn]*) exit ;;
-    *)
-        echo "Please answer 'y' or 'n'."
-        exit
-        ;;
-    esac
-done
-
-###########################################################
 #           Check if Kerberos utilities are installed
 ###########################################################
 if ! which kadmin >/dev/null 2>&1; then
@@ -141,6 +123,24 @@ klist=$(which klist)
 DESTROY_CACHE=$(which kdestroy)
 
 ###########################################################
+#           CONFIRM
+###########################################################
+echo "kcroninit creates principal ${FULLPRINCIPAL} and/or extracts its keys into a keytab."
+echo "This principal is used by the kcron utility for authentication."
+echo "You need to know the password for ${ADMPRINCIPAL} to continue."
+while true; do
+    read -r -p 'Do you want to continue? (y/n)' y_n
+    case ${y_n} in
+    [Yy]*) break ;;
+    [Nn]*) exit ;;
+    *)
+        echo "Please answer 'y' or 'n'."
+        exit
+        ;;
+    esac
+done
+
+###########################################################
 #           SET UP CREDENTIAL CACHE
 ###########################################################
 # In order to ask for password once need to obtain a ticket for kadmin/admin service
@@ -158,8 +158,11 @@ export KRB5CCNAME="KEYRING:session:${MYUID}:${SCRAMBLE}"
 ###########################################################
 #           Can write to keytab?
 ###########################################################
-echo ''
+echo 'Is keytab writable?'
 if ! KEYTAB=$(${KEYTAB_INIT}); then
+    echo ''
+    echo 'Keytab is not writable to this user:' >&2
+    id >&2
     exit 2
 fi
 
@@ -167,10 +170,10 @@ fi
 #           Run
 ###########################################################
 # Obtain credentials
-echo ''
+echo 'Trying to obtain initial credentials'
 if ! ${kinit} -c "${KRB5CCNAME}" -S kadmin/admin "${ADMPRINCIPAL}@${REALM}" >/dev/null >&2; then
     echo ''
-    echo "Failed to obtain initial credentials. Exiting..."
+    echo 'Failed to obtain initial credentials. Exiting...' >&2
     destroy
     exit 2
 fi
@@ -184,7 +187,8 @@ if [[ ${PRINCIPAL_EXIST} != '' ]]; then
     echo ''
     echo "Principal ${FULLPRINCIPAL} already exists in Kerberos database."
 else
-    echo "Creating principal..."
+    echo ''
+    echo 'Creating principal...'
     # Create principal
     ${kadmin} -p "${ADMPRINCIPAL}@${REALM}" -c "${KRB5CCNAME}" -r "${REALM}" -q "add_principal -randkey -pwexpire never ${FULLPRINCIPAL}" 2>/dev/null
 
@@ -209,9 +213,9 @@ if [[ ${PRINCIPAL_IN_KEYTAB} == '' ]]; then
     exit 2
 else
     echo ''
-    echo "Created keytab ${KEYTAB} "
+    echo "Created keytab ${KEYTAB}"
     ${klist} -k "${KEYTAB}" | grep "${FULLPRINCIPAL}"
 fi
 
 destroy
-echo DONE!
+echo 'DONE!'
