Split up mkdir from make keytab

diff --git a/src/shell/kcrondestroy b/src/shell/kcrondestroy
--- a/src/shell/kcrondestroy
+++ b/src/shell/kcrondestroy
@@ -39,7 +39,7 @@ usage() {
 ###########################################################
 destroy() {
     # Destroy credential cache
-    ${DESTROY_CACHE}
+    ${kdestroy}
     echo ''
     echo DESTROYED administration credentials.
 }
@@ -82,6 +82,12 @@ if ! which kinit >/dev/null 2>&1; then
     echo "Consider installing krb5-workstation" >&2
     exit 2
 fi
+if ! which kdestroy >/dev/null 2>&1; then
+    echo ''
+    echo "Could not find 'kdestroy'" >&2
+    echo "Consider installing krb5-workstation" >&2
+    exit 2
+fi
 if ! which logger >/dev/null 2>&1; then
     echo ''
     echo "Could not find 'logger'" >&2
@@ -103,7 +109,7 @@ fi
 
 kadmin=$(which kadmin)
 kinit=$(which kinit)
-DESTROY_CACHE=$(which kdestroy)
+kdestroy=$(which kdestroy)
 
 ###########################################################
 #           SET UP CREDENTIAL CACHE
diff --git a/src/shell/kcroninit b/src/shell/kcroninit
--- a/src/shell/kcroninit
+++ b/src/shell/kcroninit
@@ -39,7 +39,7 @@ usage() {
 ###########################################################
 destroy() {
     # Destroy credential cache
-    ${DESTROY_CACHE}
+    ${kdestroy}
     echo ''
     echo 'DESTROYED administration credentials.'
 }
@@ -98,6 +98,12 @@ if ! which klist >/dev/null 2>&1; then
     echo "Consider installing krb5-workstation" >&2
     exit 2
 fi
+if ! which kdestroy >/dev/null 2>&1; then
+    echo ''
+    echo "Could not find 'kdestroy'" >&2
+    echo "Consider installing krb5-workstation" >&2
+    exit 2
+fi
 if ! which logger >/dev/null 2>&1; then
     echo ''
     echo "Could not find 'logger'" >&2
@@ -120,7 +126,7 @@ fi
 kadmin=$(which kadmin)
 kinit=$(which kinit)
 klist=$(which klist)
-DESTROY_CACHE=$(which kdestroy)
+kdestroy=$(which kdestroy)
 
 ###########################################################
 #        CONFIRM
@@ -156,10 +162,31 @@ SCRAMBLE=$(echo "$(
 export KRB5CCNAME="KEYRING:session:${MYUID}:${SCRAMBLE}"
 
 ###########################################################
+#        Set up keytab directory and file
+###########################################################
+echo 'Initializing keytab directory...'
+if ! ${KEYTAB_DIR_INIT:-/usr/libexec/kcron/init-kerberos-client-dir}; then
+    echo ''
+    echo 'Unable to initialize client keytab directory.' >&2
+    exit 2
+fi
+
+KEYTAB=$(${KEYTAB_NAME:-/usr/libexec/kcron/client-keytab-name})
+
+if [[ ! -e ${KEYTAB} ]]; then
+    echo 'Creating empty keytab...'
+    if ! ${KEYTAB_CREATE:-/usr/libexec/kcron/create-empty-client-keytab}; then
+        echo ''
+        echo 'Unable to create empty client keytab.' >&2
+        exit 2
+    fi
+fi
+
+###########################################################
 #        Can I write to the keytab?
 ###########################################################
 echo 'Is the keytab writable?'
-if ! KEYTAB=$(${KEYTAB_INIT:-/usr/libexec/kcron/init-kcron-keytab}); then
+if [[ ! -w ${KEYTAB} ]]; then
     echo ''
     echo 'Keytab is not writable to this user:' >&2
     id >&2
